# -*- mode: ruby -*-
# vi: set ft=ruby :

##################################################
# Generated by phansible.com
##################################################

#If your Vagrant version is lower than 1.5, you can still use this provisioning
#by commenting or removing the line below and providing the config.vm.box_url parameter,
#if it's not already defined in this Vagrantfile. Keep in mind that you won't be able
#to use the Vagrant Cloud and other newer Vagrant features.
Vagrant.require_version ">= 1.5"

Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v|
        v.name = "devbox"
        v.customize [
            "modifyvm", :id,
            "--memory", 1024,
            "--natdnshostresolver1", "on",
            "--cpus", 1,
            "--ioapic", "on"
        ]
    end

    config.vm.host_name = "devbox"
    config.vm.box = "debian-7.3"
    config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/debian-73-x64-virtualbox-nocm.box"
    vconfig.vm.box_check_update = true

    config.vm.network :private_network, ip: "11.11.11.11"
    config.ssh.forward_agent = true

    #############################################################
    # Ansible provisioning (you need to have ansible installed)
    #############################################################

    if Vagrant::Util::Platform.windows?
        config.vm.provision :shell, path: "windows.sh"
    else
        config.vm.provision :ansible do |ansible|
            ansible.playbook = "ansible/playbook.yml"
            ansible.inventory_path = "ansible/devbox"
            ansible.limit = 'all'
        end
    end


    # Shared folder with NFS : you'll need nfsd
    config.vm.synced_folder "/home", "/vagrant", type: "nfs"

    # Shared folder without NFS : works with Windows host
    config.vm.synced_folder "/home/www", "/var/www", id: "vagrant-root",
        owner: "vagrant",
        group: "www-data",
        mount_options: ["dmode=775,fmode=664"]
end
