---
    php_ppa: php5-5.6
    doc_root: /var/www/
    sys_packages: ["vim","git","htop"]
    dist: precise
    php_packages: ["php5-cli","php-pear","php5-curl","php5-fpm","php5-gd","php5-intl","php5-mcrypt","php5-mysql"]
    pecl_packages: []
