---
- hosts: devbox
  sudo: true
  vars_files:
    - vars/config.yml
    - vars/mysql.yml
    - vars/mysql.yml
    - vars/nginxphp.yml
    # If Apache
    #- vars/apachephp.yml
  roles:
    - init
    - nginx
    #- apache
    - php
    - mysql
    - composer
    - app
