---
- hosts: devbox
  sudo: true
  vars:
    timezone: Europe/Paris
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - [ "vars/nginxphp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - nginx
    - php5-cli
    - php5-fpm
    - mysql
    - composer
    - phpcommon
    - app
