---
- hosts: devbox
  sudo: true
  vars:
    user: vagrant
    timezone: Europe/Paris
    servername: dev.local
    gitusername: YourName
    gitemail: your@email.com
    hostname: devbox
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - [ "vars/nginxphp.yml", "vars/ws_defaults.yml" ]
    # If Apache
    #- [ "vars/apachephp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - nginx
    #- apache
    - php
    - mysql
    - composer
    - app
